export const references = {
    1: "Convention on the Prevention and Punishment of the Crime of Genocide (adopted 9 December 1948, entered into force 12 January 1951), 78 UNTS 277.",
    2: "Raphaël Lemkin, Axis Rule in Occupied Europe: Laws of Occupation, Analysis of Government, Proposals for Redress (1944), Chapter IX.",
    3: "Geneva Convention Relative to the Protection of Civilian Persons in Time of War, 12 August 1949, 75 UNTS 287.",
    4: "Speech by Mahmoud Abbas on Palestine TV, 18 November 2023, https://www.youtube.com/watch?v=2uRGx02vULg; translated by WAFA: “President Abbas urges Biden to stop Israel’s ongoing genocide of Palestinians”, WAFA (18 November 2023), https://english.wafa.ps/Pages/Details/139394.",
    5: "United Nations Office of the High Commissioner for Human Rights (‘UN OHCHR’), Gaza: UN experts decry bombing of hospitals and schools as crimes against humanity, call for prevention of genocide (19 October 2023) https://www.ohchr.org/en/press-releases/2023/10/gaza-un-experts-decry-bombing-hospitals-and-schools-crimes-against-humanity.",
    6: "UN OHCHR, Gaza: UN experts call on international community to prevent genocide against the Palestinian people (16 November 2023), https://www.ohchr.org/en/press-releases/2023/11/gaza-un-experts-call-international-community-prevent-genocide-against.",
    7: "UN OHCHR, Gaza Strip: States are obliged to prevent crimes against humanity and genocide, UN Committee stresses (21 December 2023), https://www.ohchr.org/en/press-releases/2023/12/gaza-strip-states-are-obliged-prevent-crimes-against-humanity-and-genocide. Under CERD's Early Warning and Urgent Action (‘EWUA’) procedure, CERD has extensive expertise in compiling indicators relevant to the prevention of genocide; in 2015 it issued a Declaration on the Prevention of Genocide which recalled this work in its preamble: see CERD, Declaration on the Prevention of Genocide (CRD/C/66/1) (17 October 2005), https://www.ohchr.org/sites/default/files/Documents/HRBodies/CERD/declaration_genocide.doc (emphasis added).",
}
